<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BidFood.Domain\BidFood.Domain.csproj" />
    <ProjectReference Include="..\bidfood.infrastructure\bidfood.infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

</Project>
